### ISSUE TITLE
NPM support

### ISSUE THREAD

**Issue by RangerMauve** [gre/deprecated-glsl.js#17]
It'd be nice if this was on NPM so that it could be integrated with Browserify more easily.

**Comment by gre** [comment]
Actually I recommend to use https://www.npmjs.org/package/gl-shader
because it does a better job than glsl.js, is more maintained and goes much more far.
`gl-shader` is a bit bigger library but less hacky and specific than `glsl.js`

I think either I should turn off `glsl.js` or provide a thin wrapper on top of `gl-shader`.

**Comment by RangerMauve** [comment]
Thanks for the tip, it does seem pretty useful. GLSL has also been nice to work with however.
